<script setup>
import { onMounted, reactive, ref } from 'vue'
import { useRoute } from 'vue-router'
import { ElMessage } from 'element-plus'
import { orderApi } from '@/api/modules'

const currentRoute = useRoute()
const detail = ref(null)
const loading = ref(true)
const refundOpen = ref(false)
const reviewOpen = ref(false)
const refund = reactive({ reason: '' })
const review = reactive({ rating: 5, content: '' })
const labels = { WAIT_PAY: '待支付', PAID_WAIT_CONFIRM: '待确认', CONFIRMED: '已确认', TRAVELLING: '行程中', COMPLETED: '已完成', CANCELLED: '已取消', REFUND_APPLYING: '退款审核中', REFUND_PROCESSING: '退款处理中', REFUNDED: '已退款', REFUND_REJECTED: '退款未通过' }
async function load() { try { detail.value = await orderApi.detail(currentRoute.params.orderNo) } finally { loading.value = false } }
async function submitRefund() { await orderApi.refund(currentRoute.params.orderNo, refund); refundOpen.value = false; ElMessage.success('退款申请已提交'); load() }
async function submitReview() { await orderApi.review(currentRoute.params.orderNo, review); reviewOpen.value = false; ElMessage.success('感谢你的评价'); load() }
onMounted(load)
</script>

<template>
  <section class="page-section account-page"><div class="container narrow-container"><div v-if="loading" class="admin-panel"><el-skeleton :rows="9" animated /></div><template v-else-if="detail"><div class="detail-title-row"><div><span class="eyebrow">ORDER DETAIL</span><h2>{{ detail.route?.name || `线路 #${detail.order.routeId}` }}</h2><p>{{ detail.order.orderNo }} · 创建于 {{ detail.order.createdAt }}</p></div><span class="tag status-large">{{ labels[detail.order.status] || detail.order.status }}</span></div><div class="detail-summary-grid"><div><span>团期</span><strong>{{ detail.departure?.startDate }} 至 {{ detail.departure?.endDate }}</strong></div><div><span>联系人</span><strong>{{ detail.order.contactName }} · {{ detail.order.contactPhone }}</strong></div><div><span>出行人数</span><strong>{{ Number(detail.order.adultCount || 0) + Number(detail.order.childCount || 0) }} 人</strong></div><div><span>订单金额</span><strong class="accent">¥{{ detail.order.totalAmount }}</strong></div></div><div class="admin-panel detail-panel"><div class="section-title-row"><h3>出行人资料</h3><span>证件号码已脱敏</span></div><table class="data-table"><thead><tr><th>姓名</th><th>性别</th><th>证件</th><th>手机号</th><th>紧急联系人</th></tr></thead><tbody><tr v-for="traveler in detail.travelers" :key="traveler.id"><td>{{ traveler.name }}</td><td>{{ traveler.gender }}</td><td>{{ traveler.idType }} {{ traveler.idNoMasked }}</td><td>{{ traveler.phone || '—' }}</td><td>{{ traveler.emergencyName }} {{ traveler.emergencyPhone || '' }}</td></tr></tbody></table></div><div class="admin-panel detail-panel"><div class="section-title-row"><h3>订单状态</h3><span>支付：{{ detail.order.paymentStatus }}</span></div><div class="timeline"><div :class="{done: ['PAID_WAIT_CONFIRM','CONFIRMED','TRAVELLING','COMPLETED'].includes(detail.order.status)}"><i></i><span>订单创建</span></div><div :class="{done: ['PAID_WAIT_CONFIRM','CONFIRMED','TRAVELLING','COMPLETED'].includes(detail.order.status)}"><i></i><span>支付成功</span></div><div :class="{done: ['CONFIRMED','TRAVELLING','COMPLETED'].includes(detail.order.status)}"><i></i><span>旅行社确认</span></div><div :class="{done: ['TRAVELLING','COMPLETED'].includes(detail.order.status)}"><i></i><span>行程执行</span></div><div :class="{done: detail.order.status==='COMPLETED'}"><i></i><span>行程完成</span></div></div></div><div class="detail-actions"><button v-if="['PAID_WAIT_CONFIRM','CONFIRMED'].includes(detail.order.status)" class="secondary-button" @click="refundOpen=true">申请退款</button><button v-if="detail.order.status==='COMPLETED'" class="primary-button" @click="reviewOpen=true">评价线路</button></div></template><div v-else class="empty-box">订单不存在。</div></div></section>
  <el-dialog v-model="refundOpen" title="申请退款" width="420px"><div class="form-field"><label>退款原因</label><textarea v-model="refund.reason" rows="5" placeholder="请说明退款原因"></textarea></div><template #footer><button class="secondary-button" @click="refundOpen=false">取消</button><button class="primary-button" @click="submitRefund">提交申请</button></template></el-dialog>
  <el-dialog v-model="reviewOpen" title="评价线路" width="420px"><div class="form-field"><label>评分</label><el-rate v-model="review.rating" /></div><div class="form-field"><label>评价内容</label><textarea v-model="review.content" rows="5" placeholder="分享这次旅程"></textarea></div><template #footer><button class="secondary-button" @click="reviewOpen=false">取消</button><button class="primary-button" @click="submitReview">提交评价</button></template></el-dialog>
</template>

<style scoped>
.narrow-container{max-width:980px}.detail-title-row{display:flex;justify-content:space-between;align-items:end;gap:20px;margin-bottom:25px}.detail-title-row h2{font:500 32px Georgia,serif;margin:10px 0}.detail-title-row p{margin:0;color:var(--muted);font-size:12px}.status-large{padding:7px 12px}.detail-summary-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:1px;background:var(--line);border:1px solid var(--line);border-radius:14px;overflow:hidden;margin-bottom:20px}.detail-summary-grid>div{background:white;padding:17px}.detail-summary-grid span,.detail-summary-grid strong{display:block}.detail-summary-grid span{color:var(--muted);font-size:11px;margin-bottom:8px}.detail-summary-grid strong{font-size:13px}.detail-summary-grid .accent{color:var(--coral);font-size:20px}.detail-panel{margin-bottom:18px}.detail-panel h3{margin:0}.section-title-row{display:flex;justify-content:space-between;align-items:center;margin-bottom:15px}.section-title-row span{color:var(--muted);font-size:11px}.timeline{display:flex;justify-content:space-between;position:relative;padding:12px 0 4px}.timeline:before{content:'';position:absolute;top:22px;left:4%;right:4%;height:2px;background:#dfe9e5}.timeline>div{position:relative;z-index:1;display:grid;justify-items:center;gap:8px;color:#9baaa6;font-size:11px}.timeline i{width:18px;height:18px;border-radius:50%;background:#dfe9e5;border:5px solid white;box-shadow:0 0 0 1px #dfe9e5}.timeline .done{color:var(--teal)}.timeline .done i{background:var(--teal);box-shadow:0 0 0 1px var(--teal)}.detail-actions{text-align:right;display:flex;justify-content:end;gap:10px}@media(max-width:650px){.detail-summary-grid{grid-template-columns:1fr 1fr}.data-table{min-width:700px}.detail-title-row{align-items:start;flex-direction:column}}
</style>
